spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /health-check
        healthCheckInterval: 20s
        instanceId: ${spring.application.name}:${random.value}

server:
  port: 8765
  error:
    whitelabel:
      enabled: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.cloud.netflix: DEBUG
    com.poc.gateway: TRACE
    org.springframework.data.elasticsearch: DEBUG

zuul:
  ignoredServices: "*"
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  sensitiveHeaders: Cookie,Set-Cookie
  debug:
    request: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  ribbon:
    eager-load:
      enabled: false
  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
      sensitiveHeaders: Cookie,Set-Cookie
    data-service:
      path: /data/**
      serviceId: data-service
      sensitiveHeaders: Cookie,Set-Cookie
#      stripPrefix: false

#auth-service:
#  ribbon:
#    listOfServers: http://localhost:9091/api
#    ReadTimeout: 60000
#    ConnectTimeout: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  ServerListRefreshInterval: 1000
  eureka:
    enabled: false

# Secret to generate tokens,
auth-service:
  jwtSecret: a3ZzApRSDQF5E9cH3JFV1LNBzOtQEiv6OumGJudd3Ao=
